version: '3.3'
services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      

      - static_value:/var/html/django_static/

      - media_value:/var/html/djnago_media/
    depends_on:
      - web
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: ../backend/foodgram_backend
    restart: always
    volumes:
      - static_value:/app/django_static/
      - media_value:/app/django_media/
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  static_value:
  media_value:
