# Generated by Django 3.2 on 2022-02-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'избранное',
                'verbose_name_plural': 'избранное',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='название ингридиента', max_length=200, verbose_name='ингридиент')),
                ('measurement_unit', models.CharField(help_text='произвольная единица измерения', max_length=200, verbose_name='единица измерения')),
            ],
            options={
                'verbose_name': 'ингридиент',
                'verbose_name_plural': 'ингридиенты',
            },
        ),
        migrations.CreateModel(
            name='IngredientWithAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='количество')),
            ],
            options={
                'verbose_name': 'ингридиент с количеством',
                'verbose_name_plural': 'ингридиенты с количеством',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='название рецепта', max_length=200, verbose_name='название')),
                ('text', models.TextField(help_text='текстовое описание рецепта', verbose_name='описание')),
                ('cooking_time', models.PositiveIntegerField(help_text='время готовки в минутах', verbose_name='время готовки')),
                ('image', models.ImageField(help_text='картинка', upload_to='images/', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='название тэга', max_length=200, verbose_name='тэг')),
                ('color', models.CharField(help_text='цвет в формате HEX', max_length=7, null=True, verbose_name='цвет')),
                ('slug', models.SlugField(help_text='слаг', max_length=200, null=True, verbose_name='слаг')),
            ],
            options={
                'verbose_name': 'тэг',
                'verbose_name_plural': 'тэги',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ManyToManyField(to='food.Recipe', verbose_name='корзина')),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'корзина',
            },
        ),
    ]
